[package]
name = "email-lib"
version = "0.15.3"
description = "Rust library to manage emails."
homepage = "https://pimalaya.org/"
documentation = "https://docs.rs/email-lib/latest/email/"
repository = "https://git.sr.ht/~soywod/pimalaya/"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email", "network-programming"]
keywords = ["pim", "email", "imap", "smtp", "sendmail"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "email"

[features]
default = [
  "imap-backend",
  # "notmuch-backend",
  "smtp-sender",
  # "pgp-commands",
  # "pgp-gpg",
  # "pgp-native",
]
imap-backend = ["imap", "imap-proto", "utf7-imap"]
notmuch-backend = ["notmuch"]
smtp-sender = ["mail-send"]
pgp = []
pgp-commands = ["pgp", "mml-lib/pgp-commands"]
pgp-gpg = ["pgp", "mml-lib/pgp-gpg"]
pgp-native = ["pgp", "mml-lib/pgp-native"]

# dev dependencies

[dev-dependencies.concat-with]
version = "0.2"

[dev-dependencies.env_logger]
version = "0.10"

[dev-dependencies.tempfile]
version = "3.3"

[dev-dependencies.tokio]
version = "1.23"
default-features = false
features = ["macros", "rt", "rt-multi-thread", "time"]

# dependencies

[dependencies.advisory-lock]
version = "0.3.0"

[dependencies.anyhow]
version = "1.0"

[dependencies.async-trait]
version = "0.1"

[dependencies.chrono]
version = "0.4"

[dependencies.convert_case]
version = "0.5"

[dependencies.dirs]
version = "4.0"

[dependencies.futures]
version = "0.3"

[dependencies.log]
version = "0.4"

[dependencies.mail-builder]
version = "0.3"

[dependencies.mail-parser]
version = "0.9"

[dependencies.maildirpp]
version = "=0.0.2"

[dependencies.md5]
version = "0.7.0"

[dependencies.once_cell]
version = "1.*"

[dependencies.ouroboros]
version = "0.15"

[dependencies.mml-lib]
version = "1.0"
default-features = false
features = ["compiler", "interpreter"]

[dependencies.keyring-lib]
version = "=0.1.0"

[dependencies.oauth-lib]
version = "=0.1.0"

[dependencies.pgp-lib]
version = "=0.1.0"

[dependencies.process-lib]
version = "=0.1.0"

[dependencies.secret-lib]
version = "=0.1.0"

[dependencies.rayon]
version = "1.6"

[dependencies.regex]
version = "1.5"

[dependencies.rustls]
version = "0.21"
features = ["dangerous_configuration"]

[dependencies.rustls-native-certs]
version = "0.6"

[dependencies.shellexpand-utils]
version = "0.1.0"

[dependencies.thiserror]
version = "1.0"

[dependencies.tokio]
version = "1.23"
default-features = false
features = ["fs", "net"]

[dependencies.tokio-rustls]
version = "0.24"

[dependencies.tree_magic_mini]
version = "3.0"

[dependencies.urlencoding]
version = "2.1"

[dependencies.uuid]
version = "0.8"
features = ["v4"]

[dependencies.webpki-roots]
version = "0.25"

[dependencies.imap]
version = "=3.0.0-alpha.10"
optional = true
default-features = false
features = ["rustls-tls"]

[dependencies.imap-proto]
version = "=0.16.2"
optional = true

[dependencies.mail-send]
version = "0.4"
optional = true

[dependencies.notmuch]
version = "=0.8.0"
optional = true

[dependencies.utf7-imap]
version = "=0.3.2"
optional = true

[target.'cfg(target_env = "musl")'.dependencies.rusqlite]
version = "0.29"
features = []

[target.'cfg(not(target_env = "musl"))'.dependencies.rusqlite]
version = "0.29"
features = ["bundled"]
