[package]
name = "email-lib"
version = "0.15.2"
description = "Rust library to manage emails."
homepage = "https://pimalaya.org/"
repository = "https://git.sr.ht/~soywod/pimalaya/"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email", "network-programming"]
keywords = ["pim", "email", "imap", "smtp", "sendmail"]
metadata.docs.rs.all-features = true

[lib]
name = "email"

[features]
default = ["imap-backend", "smtp-sender", "pgp-commands"]

# backends
imap-backend = ["imap", "imap-proto", "utf7-imap"]
notmuch-backend = ["notmuch"]
pgp-native = ["mml-lib/pgp-native"]
pgp-commands = ["mml-lib/pgp-commands"]
pgp-gpg = ["mml-lib/pgp-gpg"]

# senders
smtp-sender = ["mail-send"]

[dev-dependencies.concat-with]
version = "0.2"

[dev-dependencies.env_logger]
version = "0.10"

[dev-dependencies.tempfile]
version = "3.3"

[dev-dependencies.tokio]
version = "1.23"
default-features = false
features = ["macros", "rt", "rt-multi-thread", "time"]

[dependencies.advisory-lock]
version = "0.3.0"

[dependencies.ammonia]
version = "3.2"

[dependencies.async-trait]
version = "0.1"

[dependencies.chrono]
version = "0.4"

[dependencies.convert_case]
version = "0.5"

[dependencies.dirs]
version = "4.0"

[dependencies.futures]
version = "0.3"

[dependencies.html-escape]
version = "0.2"

[dependencies.log]
version = "0.4"

[dependencies.mail-builder]
version = "=0.3.0"

[dependencies.mail-parser]
version = "=0.8.2"

[dependencies.maildirpp]
version = "=0.0.2"

[dependencies.md5]
version = "0.7.0"

[dependencies.once_cell]
version = "1.*"

[dependencies.ouroboros]
version = "0.15"

[dependencies.mml-lib]
version = "=0.2.3"
default-features = false
features = ["compiler", "interpreter"]

[dependencies.keyring-lib]
version = "=0.1.0"

[dependencies.oauth-lib]
version = "=0.1.0"

[dependencies.pgp-lib]
version = "=0.1.0"

[dependencies.process-lib]
version = "=0.1.0"

[dependencies.secret-lib]
version = "=0.1.0"

[dependencies.rayon]
version = "1.6"

[dependencies.regex]
version = "1.5"

[dependencies.rfc2047-decoder]
version = "=0.2.0"

[dependencies.rustls]
version = "0.21"
features = ["dangerous_configuration"]

[dependencies.rustls-native-certs]
version = "0.6"

[dependencies.shellexpand-utils]
version = "0.1.0"

[dependencies.thiserror]
version = "1.0"

[dependencies.tokio]
version = "1.23"
default-features = false
features = ["fs", "net"]

[dependencies.tokio-rustls]
version = "0.24"

[dependencies.tree_magic]
version = "0.2"

[dependencies.urlencoding]
version = "2.1"

[dependencies.uuid]
version = "0.8"
features = ["v4"]

[dependencies.webpki-roots]
version = "0.22"

[dependencies.imap]
version = "=3.0.0-alpha.10"
optional = true
default-features = false
features = ["rustls-tls"]

[dependencies.imap-proto]
version = "=0.16.2"
optional = true

[dependencies.mail-send]
version = "=0.4.0"
optional = true

[dependencies.notmuch]
version = "=0.8.0"
optional = true

[dependencies.utf7-imap]
version = "=0.3.2"
optional = true

[target.'cfg(target_env = "musl")'.dependencies.rusqlite]
version = "0.29"
features = []

[target.'cfg(not(target_env = "musl"))'.dependencies.rusqlite]
version = "0.29"
features = ["bundled"]
