[package]
name = "email-lib"
version = "0.22.3"
description = "Rust library to manage emails"
homepage = "https://pimalaya.org"
documentation = "https://docs.rs/email-lib/latest/email/"
repository = "https://git.sr.ht/~soywod/pimalaya/tree/master/item/email/README.md"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email", "network-programming"]
keywords = ["email", "maildir", "imap", "smtp", "sendmail"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "email"

[features]
default = [
  "imap",
  "maildir",
  # "notmuch",
  "smtp",
  "sendmail",

  "account-discovery",
  "account-sync",

  # "pgp-commands",
  # "pgp-gpg",
  # "pgp-native",
]

imap = ["dep:futures", "dep:imap", "dep:imap-proto", "dep:utf7-imap"]
maildir = ["dep:maildirpp", "dep:notify", "dep:rayon"]
notmuch = ["dep:notmuch"]
smtp = ["dep:mail-send"]
sendmail = []

account-discovery = [
  "dep:email_address",
  "dep:futures",
  "dep:hickory-resolver",
  "dep:hyper",
  "dep:hyper-rustls",
  "dep:serde-xml-rs",
]
account-sync = [
  "dep:advisory-lock",
  "dep:dirs",
  "dep:futures",
  "maildir",
]

pgp = []
pgp-commands = ["pgp", "mml-lib/pgp-commands"]
pgp-gpg = ["pgp", "mml-lib/pgp-gpg"]
pgp-native = ["pgp", "keyring-lib", "mml-lib/pgp-native", "dep:pgp-lib"]

[dev-dependencies]
concat-with = "0.2"
email-testing-server = { path = "../email-testing-server" }
env_logger = "0.10"
tempfile = "3.3"
tokio = { version = "1.23", features = ["full"] }

[dependencies]
advisory-lock = { version = "0.3", optional = true }
anyhow = "1"
async-trait = "0.1"
chrono = "0.4"
convert_case = "0.5"
dirs = { version = "4.0", optional = true }
email-macros = "=0.0.2"
email_address = { version = "0.2", optional = true, default-features = false }
futures = { version = "0.3", optional = true }
hickory-resolver = { version = "0.24", optional = true, features = ["dns-over-rustls"] }
hyper = { version = "0.14", optional = true, default-features = false, features = [ "http1", "http2" ] }
hyper-rustls = { version = "0.24", optional = true }
imap = { version = "=3.0.0-alpha.12", optional = true, default-features = false, features = ["rustls-tls"] }
imap-proto = { version = "=0.16.3", optional = true }
keyring-lib = { version = "=0.3.2", optional = true }
log = "0.4"
mail-builder = "0.3"
mail-parser = "0.9"
mail-send = { version = "0.4", optional = true }
maildirpp = { version = "=0.0.2", optional = true }
md5 = "0.7"
mml-lib = { version = "=1.0.7", default-features = false, features = ["compiler", "interpreter"] }
notify = { version = "6", optional = true, default-features = false, features = ["macos_kqueue"] }
notify-rust = "4"
notmuch = { version = "=0.8.0", optional = true }
oauth-lib = "=0.1.0"
once_cell = "1"
ouroboros = "0.15"
paste = "1"
pgp-lib = { version = "=0.1.0", optional = true }
process-lib = "=0.3.1"
rayon = { version = "1.6", optional = true }
regex = "1.5"
secret-lib = "=0.3.3"
serde = { version = "1", features = ["derive"] }
serde-xml-rs = { version = "0.6", optional = true }
shellexpand-utils = "=0.2.0"
thiserror = "1"
tokio = { version = "1.23", default-features = false, features = ["macros", "fs", "net"] }
tokio-rustls = "0.25"
tree_magic_mini = "3"
urlencoding = "2.1"
utf7-imap = { version = "=0.3.2", optional = true }

[target.'cfg(unix)'.dependencies]
chumsky = { version = "=1.0.0-alpha.6", features = ["label"] }

[target.'cfg(windows)'.dependencies]
chumsky = { version = "=1.0.0-alpha.6", default-features = false, features = ["std", "label"] }
