[package]
name = "pimalaya-email"
version = "0.7.1"
description = "Rust library to manage your emails."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email", "network-programming"]
keywords = ["pim", "email", "imap", "smtp", "sendmail"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "pimalaya_email"

[features]
default = ["rustls-tls", "rustls-native-certs", "imap-backend", "smtp-sender"]

# rustls tls
rustls-tls = ["rustls", "webpki-roots", "imap/rustls-tls", "lettre/rustls-tls"]
rustls-native-certs = ["dep:rustls-native-certs", "rustls-tls"]

# native tls
native-tls = ["dep:native-tls", "imap/native-tls", "lettre/native-tls"]
native-tls-vendored = ["native-tls", "native-tls/vendored"]

# backends
imap-backend = ["imap", "imap-proto", "utf7-imap"]
notmuch-backend = ["notmuch"]

# senders
smtp-sender = []

[dev-dependencies]
concat-with = "0.2"
criterion = "0.4"
env_logger = "0.10"
tempfile = "3.3"

[dependencies]
ammonia = "3.2"
chrono = "0.4"
convert_case = "0.5"
dirs = "4.0"
html-escape = "0.2"
keyring = "2.0.2"
lettre = { version = "=0.10.2", default-features = false, features = ["smtp-transport", "pool", "hostname", "builder", "serde"] }
log = "0.4"
mail-parser = "0.8.1"
maildir = { version = "=0.6.3", features = ["mmap"] }
mailparse = "0.14"
md5 = "0.7.0"
mime-msg-builder = "0.1.0"
once_cell = "1.*"
ouroboros = "0.15"
pimalaya-oauth2 = { path = "../oauth2" }
proc-lock = "0.4"
rayon = "1.6"
regex = "1.5"
rfc2047-decoder = "=0.2.0"
shellexpand = "2.1"
thiserror = "1.0"
tree_magic = "0.2"
urlencoding = "2.1"
uuid = { version = "0.8", features = ["v4"] }

# [dependencies.optional]
imap = { version = "=3.0.0-alpha.9", optional = true, default-features = false }
imap-proto = { version = "=0.16.2", optional = true }
native-tls = { version = "0.2", optional = true }
notmuch = { version = "=0.8.0", optional = true }
utf7-imap = { version = "=0.3.2", optional = true }

rustls = { version = "0.20", optional = true, features = ["dangerous_configuration"] }
rustls-native-certs = { version = "0.6", optional = true }
webpki-roots = { version = "0.22", optional = true }

[target.'cfg(target_env = "musl")'.dependencies]
rusqlite = { version = "0.29.0", features = [] }

[target.'cfg(not(target_env = "musl"))'.dependencies]
rusqlite = { version = "0.29.0", features = ["bundled"] }

[[bench]]
name = "sync"
harness = false
