[package]
name = "pimalaya-email"
version = "0.9.1-beta"
description = "Rust library to manage your emails."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email", "network-programming"]
keywords = ["pim", "email", "imap", "smtp", "sendmail"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "pimalaya_email"

[features]
default = ["imap-backend", "smtp-sender"]

# backends
imap-backend = ["imap", "imap-proto", "utf7-imap"]
notmuch-backend = ["notmuch"]

# senders
smtp-sender = []

[dev-dependencies]
concat-with = "0.2"
criterion = "0.4"
env_logger = "0.10"
tempfile = "3.3"

[dependencies]
advisory-lock = "0.3.0"
ammonia = "3.2"
chrono = "0.4"
convert_case = "0.5"
dirs = "4.0"
html-escape = "0.2"
log = "0.4"
mail-builder = "=0.3.0"
mail-parser = "=0.8.2"
mail-send = "=0.4.0"
maildirpp = "=0.0.2"
md5 = "0.7.0"
once_cell = "1.*"
ouroboros = "0.15"
pimalaya-email-tpl = "=0.2.0"
pimalaya-oauth2 = "=0.0.3"
pimalaya-process = "=0.0.2"
pimalaya-secret = "=0.0.2"
rayon = "1.6"
regex = "1.5"
rfc2047-decoder = "=0.2.0"
rustls = { version = "0.21", features = ["dangerous_configuration"] }
rustls-native-certs = "0.6"
shellexpand = "2.1"
thiserror = "1.0"
tokio = { version = "1.23", default-features = false, features = ["rt"] }
tokio-rustls = "0.24"
tree_magic = "0.2"
urlencoding = "2.1"
uuid = { version = "0.8", features = ["v4"] }
webpki-roots = "0.22"

# [dependencies.optional]
imap = { version = "=3.0.0-alpha.10", optional = true, default-features = false, features = ["rustls-tls"] }
imap-proto = { version = "=0.16.2", optional = true }
notmuch = { version = "=0.8.0", optional = true }
utf7-imap = { version = "=0.3.2", optional = true }

[target.'cfg(target_env = "musl")'.dependencies]
rusqlite = { version = "0.29", features = [] }
[target.'cfg(not(target_env = "musl"))'.dependencies]
rusqlite = { version = "0.29", features = ["bundled"] }

[[bench]]
name = "sync"
harness = false
