[workspace]
resolver = "2"
members = [
  "email",
  "email-macros",
  "email-testing-server",
  "http",
  "keyring",
  "mml",
  "oauth",
  "pgp",
  "process",
  "secret",
  "shellexpand-utils",
  "time",
]

[patch.crates-io]
email-lib = { path = "./email" }
email-macros = { path = "./email-macros" }
http-lib = { path = "./http" }
keyring-lib = { path = "./keyring" }
mml-lib = { path = "./mml" }
oauth-lib = { path = "./oauth" }
pgp-lib = { path = "./pgp" }
process-lib = { path = "./process" }
secret-lib = { path = "./secret" }
shellexpand-utils = { path = "./shellexpand-utils" }
time-lib = { path = "./time" }

# IMAP
imap-next = { git = "https://github.com/duesee/imap-next" }
imap-client = { git = "https://github.com/pimalaya/imap-client" }
