[workspace]
resolver = "2"
members = [
  "email",
  "email-macros",
  "keyring",
  "maildir++",
  "mml",
  "oauth",
  "pgp",
  "process",
  "secret",
  "shellexpand-utils",
  "time",
]

[patch.crates-io]
email-macros = { path = "./email-macros" }
