[workspace]
resolver = "2"
members = [
  "email",
  "email-macros",
  "email-testing-server",
  "keyring",
  "maildir++",
  "mml",
  "oauth",
  "pgp",
  "process",
  "secret",
  "shellexpand-utils",
  "time",
]

[patch.crates-io]
chumsky = { git = "https://github.com/zesterer/chumsky.git", rev = "6837537" }
email-macros = { path = "./email-macros" }
keyring-lib = { path = "./keyring" }
mml-lib = { path = "./mml" }
secret-lib = { path = "./secret" }
