[workspace]
resolver = "2"
members = [
  "email",
  "email-macros",
  "email-testing-server",
  "keyring",
  "m2dir",
  "maildir++",
  "mml",
  "oauth",
  "pgp",
  "process",
  "secret",
  "shellexpand-utils",
  "time",
]

[patch.crates-io]
email-lib = { path = "./email" }
email-macros = { path = "./email-macros" }
keyring-lib = { path = "./keyring" }
maildirpp = { path = "./maildir++" }
mml-lib = { path = "./mml" }
oauth-lib = { path = "./oauth" }
pgp-lib = { path = "./pgp" }
process-lib = { path = "./process" }
secret-lib = { path = "./secret" }
shellexpand-utils = { path = "./shellexpand-utils" }
time-lib = { path = "./time" }

# imap-client = { path = "/home/soywod/code/imap-client" }
# maildirs = { path = "/home/soywod/sourcehut/maildirs" }
