[package]
name = "pimalaya-pgp"
version = "0.0.1"
description = "Rust library to abstract and simplify PGP actions."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = []
keywords = ["pgp", "gpg", "encrypt", "decrypt", "sign"]

[lib]
name = "pimalaya_pgp"

[features]
commands = ["pimalaya-process"]
gpg = ["gpgme"]
native = ["pgp", "pimalaya-keyring", "rand", "smallvec"]
default = ["commands", "gpg", "native"]

[dev-dependencies]
concat-with = "0.2"
env_logger = "0.10"
tempfile = "3.3"
tokio = { version = "1.23", default-features = false, features = ["macros", "rt"] }

[dependencies]
log = "0.4"
thiserror = "1.0"

gpgme = { version = "=0.11.0", optional = true }
pgp = { version = "0.10", optional = true }
pimalaya-keyring = { version = "=0.0.5", optional = true }
pimalaya-process = { version = "=0.0.5", optional = true }
rand = { version = "0.8", optional = true }
smallvec = { version = "1", optional = true }
