[package]
name = "pgp-lib"
version = "0.2.0"
description = "Rust library to deal with PGP operations"
homepage = "https://pimalaya.org/"
documentation = "https://docs.rs/pgp-lib/latest/pgp/"
repository = "https://git.sr.ht/~soywod/pimalaya/tree/master/item/pgp/README.md"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = []
keywords = ["pgp", "openpgp", "encrypt", "decrypt", "sign"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "pgp"

[dev-dependencies]
concat-with = "0.2"
env_logger = "0.10"
tempfile = "3.3"
tokio = { version = "1.23", default-features = false, features = ["macros", "rt"] }

[dependencies]
async-recursion = "1"
futures = "0.3"
hyper = { version = "0.14", default-features = false, features = [ "http1", "http2" ] }
hyper-rustls = "0.24"
log = "0.4"
pgp_native = { version = "0.10", package = "pgp" }
rand = "0.8"
sha1 = "0.10"
smallvec = "1"
thiserror = "1"
tokio = { version = "1.23", default-features = false, features = ["rt"] }
url = "2.4"
z-base-32 = "0.1"
