[package]
name = "pimalaya-pgp"
version = "0.0.1"
description = "Rust library to simplify native PGP operations."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = []
keywords = ["pgp", "openpgp", "encrypt", "decrypt", "sign"]

[lib]
name = "pimalaya_pgp"

[dev-dependencies]
concat-with = "0.2"
env_logger = "0.10"
tempfile = "3.3"
tokio = { version = "1.23", default-features = false, features = ["macros", "rt"] }

[dependencies]
async-recursion = "1.0"
futures = "0.3"
hyper = { version = "0.14", default-features = false, features = [ "http1", "http2" ] }
hyper-rustls = "0.24"
log = "0.4"
pgp = "0.10"
rand = "0.8"
sha1 = "0.10"
smallvec = "1"
thiserror = "1.0"
tokio = { version = "1.23", default-features = false, features = ["rt"] }
url = "2.4"
z-base-32 = "0.1"
