[package]
name = "mml-lib"
version = "1.0.0"
description = "Rust implementation of the Emacs MIME message Meta Language (MML)."
homepage = "https://pimalaya.org/"
documentation = "https://docs.rs/mml-lib/latest/mml/"
repository = "https://git.sr.ht/~soywod/pimalaya/"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email", "text-processing"]
keywords = ["email", "mime", "message", "mml", "emacs"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "mml"

[features]
default = [
  "compiler",
  "interpreter",
  # "pgp-commands",
  # "pgp-gpg",
  # "pgp-native",
]
compiler = ["chumsky", "shellexpand-utils", "tree_magic_mini"]
interpreter = ["nanohtml2text"]
pgp = []
pgp-commands = ["pgp", "process-lib"]
pgp-gpg = ["pgp", "gpgme"]
pgp-native = ["pgp", "pgp-lib", "keyring-lib", "secret-lib", "shellexpand-utils"]

# dev dependencies

[dev-dependencies.concat-with]
version = "0.2"

[dev-dependencies.env_logger]
version = "0.10"

[dev-dependencies.tempfile]
version = "3.8"

[dev-dependencies.tokio]
version = "1.23"
default-features = false
features = ["fs", "macros", "rt-multi-thread"]

# dependencies

[dependencies.async-recursion]
version = "1.0"

[dependencies.log]
version = "0.4"

[dependencies.mail-builder]
version = "0.3"

[dependencies.mail-parser]
version = "0.9"

[dependencies.thiserror]
version = "1.0"

# compiler dependencies

[target.'cfg(unix)'.dependencies.chumsky]
version = "1.0.0-alpha.4"
optional = true
features = ["label"]

[target.'cfg(windows)'.dependencies.chumsky]
version = "1.0.0-alpha.4"
optional = true
default-features = false
features = ["std", "label"]

[dependencies.nanohtml2text]
version = "0.1"
optional = true

# interpreter dependencies

[dependencies.tree_magic_mini]
version = "3.0"
optional = true

# pgp-commands dependencies

[dependencies.process-lib]
version = "=0.1.0"
optional = true

# pgp-gpg dependencies

[dependencies.gpgme]
version = "0.11"
optional = true

# pgp-native dependencies

[dependencies.keyring-lib]
version = "=0.1.0"
optional = true

[dependencies.secret-lib]
version = "=0.1.0"
optional = true

[dependencies.pgp-lib]
version = "=0.1.0"
optional = true

[dependencies.shellexpand-utils]
version = "0.1.0"
optional = true
