[package]
name = "mml-lib"
version = "0.2.3"
description = "Rust implementation of the Emacs MIME message Meta Language (MML)."
homepage = "https://pimalaya.org/"
repository = "https://git.sr.ht/~soywod/pimalaya/"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email", "text-processing"]
keywords = ["email", "mime", "message", "mml", "emacs"]

[lib]
name = "mml"

[features]
all = ["compiler", "interpreter", "pgp-commands", "pgp-gpg", "pgp-native"]
default = ["compiler", "interpreter"]
compiler = ["chumsky", "shellexpand-utils", "tree_magic_mini"]
interpreter = ["nanohtml2text"]
pgp = ["pgp-commands"]
pgp-commands = ["pgp", "process-lib"]
pgp-gpg = ["pgp", "gpgme"]
pgp-native = ["pgp", "pgp-lib", "keyring-lib", "secret-lib", "shellexpand-utils"]

[dev-dependencies.concat-with]
version = "0.2"

[dev-dependencies.env_logger]
version = "0.10"

[dev-dependencies.tempfile]
version = "3.3"

[dev-dependencies.tokio]
version = "1.23"
default-features = false
features = ["fs", "macros", "rt"]

[dependencies.async-recursion]
version = "1.0"

[dependencies.log]
version = "0.4"

[dependencies.mail-builder]
version = "=0.3.0"

[dependencies.mail-parser]
version = "=0.8.2"

[dependencies.thiserror]
version = "1.0"

# compiler feature

[dependencies.nanohtml2text]
version = "0.1"
optional = true

[target.'cfg(windows)'.dependencies.chumsky]
version = "1.0.0-alpha.4"
optional = true
default-features = false
features = ["std", "label"]

[target.'cfg(not(windows))'.dependencies.chumsky]
version = "1.0.0-alpha.4"
optional = true
features = ["label"]

# interpreter feature

[dependencies.tree_magic_mini]
version = "3.0"
optional = true

# pgp-commands feature

[dependencies.process-lib]
version = "=0.1.0"
optional = true

# pgp-gpg feature

[dependencies.gpgme]
version = "0.11"
optional = true

# pgp-native feature

[dependencies.keyring-lib]
version = "=0.1.0"
optional = true

[dependencies.secret-lib]
version = "=0.1.0"
optional = true

[dependencies.pgp-lib]
version = "=0.1.0"
optional = true

[dependencies.shellexpand-utils]
version = "0.1.0"
optional = true
