[package]
name = "mml-lib"
version = "0.1.0"
description = "Rust implementation of the Emacs MIME message Meta Language (MML)."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email", "text-processing"]
keywords = ["email", "mime", "message", "mml", "emacs"]

[lib]
name = "mml"

[features]
default = ["compiler", "interpreter", "pgp-cmds"]
compiler = ["chumsky", "shellexpand", "tree_magic"]
interpreter = ["nanohtml2text"]
pgp = ["pgp-cmds"]
pgp-cmds = ["pgp", "pimalaya-process"]
pgp-gpg = ["pgp", "gpgme"]
pgp-native = ["pgp", "pimalaya-keyring", "pimalaya-pgp", "pimalaya-secret", "shellexpand"]

[dev-dependencies]
concat-with = "0.2"
env_logger = "0.10"
tempfile = "3.3"
tokio = { version = "1.23", default-features = false, features = ["fs", "macros", "rt"] }

[dependencies]
async-recursion = "1.0"
log = "0.4"
mail-builder = "=0.3.0"
mail-parser = "=0.8.2"
thiserror = "1.0"

# compiler feature
chumsky = { version = "0.9", optional = true }
nanohtml2text = { version = "0.1", optional = true}

# interpreter feature
tree_magic = { version = "0.2", optional = true }

# pgp-cmd feature
pimalaya-process = { path = "../process", optional = true }

# pgp-native feature
pimalaya-keyring = { path = "../keyring", optional = true }
pimalaya-pgp = { path = "../pgp", optional = true }
pimalaya-secret = { path = "../secret", optional = true }
shellexpand = { version = "2.1", optional = true }

# pgp-gpg feature
gpgme = { version = "0.11", optional = true }
