[package]
name = "mml-lib"
version = "0.1.2"
description = "Rust implementation of the Emacs MIME message Meta Language (MML)."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["email", "text-processing"]
keywords = ["email", "mime", "message", "mml", "emacs"]

[lib]
name = "mml"

[features]
default = ["compiler", "interpreter", "pgp-cmds"]
compiler = ["chumsky", "shellexpand", "tree_magic"]
interpreter = ["nanohtml2text"]
pgp = ["pgp-cmds"]
pgp-cmds = ["pgp", "pimalaya-process"]
pgp-gpg = ["pgp", "gpgme"]
pgp-native = ["pgp", "pgp-lib", "pimalaya-keyring", "pimalaya-secret", "shellexpand"]

[dev-dependencies]
concat-with = "0.2"
env_logger = "0.10"
tempfile = "3.3"
tokio = { version = "1.23", default-features = false, features = ["fs", "macros", "rt"] }

[dependencies]
async-recursion = "1.0"
log = "0.4"
mail-builder = "=0.3.0"
mail-parser = "=0.8.2"
thiserror = "1.0"

# pgp-cmds feature
pimalaya-process.version = "=0.0.5"
pimalaya-process.optional = true

# pgp-native feature
pimalaya-keyring.version = "=0.0.5"
pimalaya-keyring.optional = true

pimalaya-secret.version = "=0.0.5"
pimalaya-secret.optional = true

pgp-lib.version = "=0.0.1"
pgp-lib.optional = true

shellexpand.version = "2.1"
shellexpand.optional = true

# pgp-gpg feature
gpgme.version = "0.11"
gpgme.optional = true

# interpreter feature
tree_magic.version = "0.2"
tree_magic.optional = true

# compiler feature
nanohtml2text.version = "0.1"
nanohtml2text.optional = true

[target.'cfg(windows)'.dependencies]
chumsky.version = "0.9"
chumsky.optional = true
chumsky.default-features = false
chumsky.features = ["std"]

[target.'cfg(not(windows))'.dependencies]
chumsky.version = "0.9"
chumsky.optional = true
