[package]
name = "pimalaya-keyring"
version = "0.0.5-beta"
description = "Rust library to manage keyring for the Pimalaya project."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["configuration", "database interfaces"]
keywords = ["pim", "keyring", "password", "secret", "token"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "pimalaya_keyring"

[dev-dependencies]
env_logger = "0.10"

[dependencies]
keyring = { version = "2.0.4", default-features = false, features = ["linux-secret-service-rt-tokio-crypto-rust"] }
log = "0.4"
thiserror = "1.0"
