[package]
name = "keyring-lib"
version = "0.2.0"
description = "High-level API for keyring, a cross-platform library to manage secrets"
homepage = "https://pimalaya.org/"
repository = "https://git.sr.ht/~soywod/pimalaya/tree/master/item/keyring/README.md"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["config", "database"]
keywords = ["password", "credential", "keychain", "keyring", "cross-platform"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "keyring"

[dev-dependencies]
env_logger = "0.10"

[dependencies]
keyring_native = { version = "2", package = "keyring", default-features = false, features = ["linux-secret-service-rt-tokio-crypto-rust"] }
log = "0.4"
once_cell = "1"
secret-service = "3"
thiserror = "1"
