[package]
name = "keyring-lib"
version = "0.4.2"
description = "High-level API for keyring-rs, a cross-platform library to manage secrets"
homepage = "https://pimalaya.org/"
repository = "https://git.sr.ht/~soywod/pimalaya/tree/master/item/keyring/README.md"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["config", "database"]
keywords = ["password", "credential", "keychain", "keyring", "cross-platform"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--document-private-items"]

[lib]
name = "keyring"

[features]
default = [
  "tokio",
  # "tokio-openssl",
  
  # "async-io",
  # "async-io-openssl",
  
  # "derive",
]

tokio = ["keyring_native/linux-secret-service-rt-tokio-crypto-rust"]
tokio-openssl = ["keyring_native/linux-secret-service-rt-tokio-crypto-openssl"]

async-io = ["keyring_native/linux-secret-service-rt-async-io-crypto-rust"]
async-io-openssl = ["keyring_native/linux-secret-service-rt-async-io-crypto-openssl"]

derive = ["dep:serde", "serde/derive"]

[dev-dependencies]
env_logger = "0.10"
tokio = { version = "1.23", features = ["full"] }

[dependencies]
keyring_native = { version = "2", package = "keyring", default-features = false }
log = "0.4"
once_cell = "1"
serde = { version = "1", optional = true }
thiserror = "1"
tokio = { version = "1.23", default-features = false }

[target.'cfg(target_os = "linux")'.dependencies]
keyring_native = { version = "2", package = "keyring", default-features = false, features = ["linux-keyutils"] }
