[package]
name = "keyring-lib"
version = "0.1.0"
description = "Rust library to manage your sensitive data."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["configuration", "database interfaces"]
keywords = ["pim", "keyring", "password", "secret", "token"]
metadata.docs.rs.all-features = true

[lib]
name = "keyring"

[dev-dependencies.env_logger]
version = "0.10"

[dependencies.keyring_native]
package = "keyring"
version = "2.0.4"
default-features = false
features = ["linux-no-secret-service"]

[dependencies.log]
version = "0.4"

[dependencies.thiserror]
version = "1.0"
