[package]
name = "pimalaya-keyring"
version = "0.0.1"
description = "Rust library to manage keyring for the Pimalaya project."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["configuration", "database interfaces"]
keywords = ["pim", "keyring", "password-manager", "secret"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "pimalaya_keyring"

[dependencies]
keyring = "2.0.2"
log = "0.4"
thiserror = "1.0"
