[package]
name = "keyring-lib"
description = "High-level API for keyring-rs, a cross-platform library to manage credentials"
version = "1.0.0"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["config", "database"]
keywords = ["password", "credential", "keychain", "keyring", "cross-platform"]
homepage = "https://pimalaya.org/"
documentation = "https://docs.rs/keyring-lib/latest/keyring/"
repository = "https://github.com/pimalaya/core/tree/master/keyring/"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs", "--document-private-items"]

[lib]
name = "keyring"

[features]
default = [
  "rustls",
  #"openssl",
  #"derive",
]

# Rust crypto
#
rustls = ["native/crypto-rust"]
openssl = ["native/crypto-openssl"]

# Serde (de)serialization
#
derive = ["dep:serde"]

[dev-dependencies]
test-log = { version = "0.2", default-features = false, features = ["color", "trace"] }
tokio = { version = "1.23", features = ["full"] }

[dependencies]
native = { package = "keyring", version = "3", git = "https://github.com/soywod/keyring-rs.git", branch = "secret-service-with-keyutils", default-features = false, features = ["linux-native-async-persistent", "apple-native", "windows-native", "tokio"] }
once_cell = "1"
serde = { version = "1", optional = true, features = ["derive"] }
thiserror = "1"
tokio = { version = "1.23", default-features = false }
tracing = "0.1"
