[package]
name = "secret-lib"
version = "0.2.0"
description = "Rust library to retrieve secrets from different sources"
homepage = "https://pimalaya.org/"
repository = "https://git.sr.ht/~soywod/pimalaya/tree/master/item/secret/README.md"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["config", "data-structures"]
keywords = ["pim", "keyring", "oauth2", "password", "secret"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "secret"

[dev-dependencies]
tokio = { version = "1.23", default-features = false, features = ["macros", "rt"] }

[dependencies]
keyring-lib = "=0.2.0"
process-lib = "=0.2.0"
thiserror = "1"
