[package]
name = "secret-lib"
version = "0.1.0"
description = "Rust library to retrieve secrets from different sources."
homepage = "https://pimalaya.org/"
repository = "https://git.sr.ht/~soywod/pimalaya/"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["config", "data-structures"]
keywords = ["pim", "keyring", "oauth2", "password", "secret"]
metadata.docs.rs.all-features = true

[lib]
name = "secret"

[dev-dependencies.env_logger]
version = "0.10"

[dev-dependencies.tokio]
version = "1.23"
default-features = false
features = ["macros", "rt"]

[dependencies.log]
version = "0.4"

[dependencies.thiserror]
version = "1.0"

[dependencies.keyring-lib]
version = "=0.1.0"

[dependencies.process-lib]
version = "=0.1.0"

