[package]
name = "pimalaya-secret"
version = "0.0.6-beta"
description = "Rust library to manage secrets for the Pimalaya project."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["config", "data-structures"]
keywords = ["pim", "keyring", "oauth2", "password", "secret"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "pimalaya_secret"

[dev-dependencies]
env_logger = "0.10"
tokio = { version = "1.23", default-features = false, features = ["macros", "rt"] }

[dependencies]
log = "0.4"
pimalaya-keyring = { path = "../keyring" }
pimalaya-process = { path = "../process" }
thiserror = "1.0"
