[package]
name = "pimalaya-secret"
version = "0.0.1"
description = "Rust library to manage secrets related to the Pimalaya project."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["configuration", "data structures"]
keywords = ["pim", "keyring", "oauth2", "password", "secret"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "pimalaya_secret"

[dependencies]
log = "0.4"
pimalaya-keyring = { path = "../keyring" }
pimalaya-oauth2 = { path = "../oauth2" }
pimalaya-process = { path = "../process" }
thiserror = "1.0"
