[package]
name = "pimalaya-secret"
version = "0.0.2"
description = "Rust library to manage secrets for the Pimalaya project."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["configuration", "data structures"]
keywords = ["pim", "keyring", "oauth2", "password", "secret"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "pimalaya_secret"

[dependencies]
log = "0.4"
pimalaya-keyring = "=0.0.4"
pimalaya-oauth2 = "=0.0.2"
pimalaya-process = "=0.0.2"
thiserror = "1.0"
