[package]
name = "pimalaya-time"
version = "0.0.2"
description = "Rust library to manage your time."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["network-programming"]
keywords = ["pim", "pomodoro", "time", "management", "technique"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "pimalaya_time"

[features]
default = ["server", "client", "tcp"]

server = []
client = []

tcp-binder = ["server"]
tcp-client = ["client"]
tcp = ["tcp-binder", "tcp-client"]

[dev-dependencies]
env_logger = "0.10.0"

[dependencies]
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
