[package]
name = "time-lib"
version = "0.1.1"
description = "Rust library to manage time"
homepage = "https://pimalaya.org/"
documentation = "https://docs.rs/time-lib/latest/time/"
repository = "https://git.sr.ht/~soywod/pimalaya/tree/master/item/time/README.md"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["network-programming"]
keywords = ["pim", "pomodoro", "time", "management", "technique"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "time"

[features]
default = [
  "server",
  "client",
  "tcp-full",
]

server = []
client = []

tcp = []
tcp-binder = ["tcp", "server"]
tcp-client = ["tcp", "client"]
tcp-full = ["tcp-binder", "tcp-client"]

[dev-dependencies]
env_logger = "0.10"
mock_instant = "0.3"
tokio = { version = "1.23", default-features = false, features = ["full"] }

[dependencies]
async-trait = "0.1"
log = "0.4"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1.23", default-features = false, features = ["rt", "time", "net", "io-util"] }
