[package]
name = "time-lib"
version = "0.1.0"
description = "Rust library to manage time."
homepage = "https://pimalaya.org/"
documentation = "https://docs.rs/time-lib/latest/time/"
repository = "https://git.sr.ht/~soywod/pimalaya/"
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["network-programming"]
keywords = ["pim", "pomodoro", "time", "management", "technique"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[lib]
name = "time"

[features]
default = ["server", "client", "tcp"]
server = []
client = []
tcp-binder = ["server"]
tcp-client = ["client"]
tcp = ["tcp-binder", "tcp-client"]

[dev-dependencies.env_logger]
version = "0.10"

[dev-dependencies.mock_instant]
version = "0.3"

[dependencies.log]
version = "0.4"

[dependencies.serde]
version = "1.0"
features = ["derive"]

[dependencies.serde_json]
version = "1.0"
