[package]
name = "process-lib"
version = "0.1.0"
description = "Rust library to run cross-platform, asynchronous processes in pipelines."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["asynchronous"]
keywords = ["command", "process", "pipeline", "cross-platform", "async"]
metadata.docs.rs.all-features = true

[lib]
name = "process"

[dev-dependencies.env_logger]
version = "0.10"

[dev-dependencies.tokio]
version = "1.23"
default-features = false
features = ["macros", "rt"]

[dependencies.log]
version = "0.4"

[dependencies.thiserror]
version = "1.0"

[dependencies.tokio]
version = "1.23"
default-features = false
features = ["io-util", "process"]
