[package]
name = "pimalaya-process"
version = "0.0.3-beta"
description = "Rust library to run cross-platform, asynchronous processes in pipelines."
authors = ["soywod <clement.douin@posteo.net>"]
edition = "2021"
license = "MIT"
categories = ["operating systems"]
keywords = ["pim", "process", "pipeline", "crossplatform", "async"]

[package.metadata.docs.rs]
all-features = true

[lib]
name = "pimalaya_process"

[dev-dependencies]
env_logger = "0.10"
tokio = { version = "1.23", default-features = false, features = ["macros", "rt"] }

[dependencies]
log = "0.4"
thiserror = "1.0"
tokio = { version = "1.23", default-features = false, features = ["io-util", "process"] }
